package myclass;
import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

/**
 *
 * @author Home
 */
public class studentData extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rSet;
    String sId, sName, sGpa;
    int curRow = 0;
    
    DefaultListModel dlm = new DefaultListModel();
    public studentData() {
        initComponents();
        connectMe();
        showList();
    }
    
    public void displayMe() throws SQLException{
        int id = rSet.getInt("idNumber");
        String name = rSet.getString("name");
        Double gpa = rSet.getDouble("gpa");
        
        idNumTxt.setText(Integer.toString(id));
        nameTxt.setText(name);
        gpaTxt.setText(Double.toString(gpa));
    }
    public void connectMe()
    {
        try{
            String url = "jdbc:derby://localhost:1527/StudentDatabase";
            String uName = "mikhamirna";
            String password = "mikhamirna";
            con = DriverManager.getConnection(url, uName, password);
            
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "select * from studenttable";
            rSet = stmt.executeQuery(query);
            
            rSet.next();
            displayMe();
            
        }catch(SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }
    public void showList()
    {
        try
        {
            do
            {
                String name = rSet.getString("name");
                dlm.addElement(name);
            }while(rSet.next());
            nameList.setModel(dlm);
        }catch(SQLException err)
        {
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idNumTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        gpaTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        firstButt = new javax.swing.JButton();
        lastButt = new javax.swing.JButton();
        nextButt = new javax.swing.JButton();
        prevButt = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        newButt = new javax.swing.JButton();
        updateButt = new javax.swing.JButton();
        deleteButt = new javax.swing.JButton();
        saveButt = new javax.swing.JButton();
        cancelButt = new javax.swing.JButton();
        exitButt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nameList = new javax.swing.JList<>();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        
        jLabel1.setText("ID Number");
        
        jLabel2.setText("Name");
        
        jLabel3.setText("GPA");
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                                         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                         .addGroup(jPanel1Layout.createSequentialGroup()
                                                   .addGap(21, 21, 21)
                                                   .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                             .addComponent(jLabel3)
                                                             .addComponent(jLabel2)
                                                             .addComponent(jLabel1))
                                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                   .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                             .addComponent(idNumTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                             .addComponent(nameTxt)
                                                             .addComponent(gpaTxt))
                                                   .addGap(19, 19, 19))
                                         );
        jPanel1Layout.setVerticalGroup(
                                       jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel1Layout.createSequentialGroup()
                                                 .addGap(11, 11, 11)
                                                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                           .addComponent(jLabel1)
                                                           .addComponent(idNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                           .addComponent(jLabel2)
                                                           .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                           .addComponent(jLabel3)
                                                           .addComponent(gpaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                 .addContainerGap(19, Short.MAX_VALUE))
                                       );
        
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        
        firstButt.setText("First");
        firstButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtActionPerformed(evt);
            }
        });
        
        lastButt.setText("Last");
        lastButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtActionPerformed(evt);
            }
        });
        
        nextButt.setText("Next");
        nextButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtActionPerformed(evt);
            }
        });
        
        prevButt.setText("Prev");
        prevButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                                         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                         .addGroup(jPanel2Layout.createSequentialGroup()
                                                   .addContainerGap()
                                                   .addComponent(firstButt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                   .addGap(18, 18, 18)
                                                   .addComponent(nextButt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                   .addGap(18, 18, 18)
                                                   .addComponent(prevButt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                   .addGap(18, 18, 18)
                                                   .addComponent(lastButt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                   .addContainerGap(7, Short.MAX_VALUE))
                                         );
        jPanel2Layout.setVerticalGroup(
                                       jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel2Layout.createSequentialGroup()
                                                 .addContainerGap()
                                                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                           .addComponent(firstButt)
                                                           .addComponent(lastButt)
                                                           .addComponent(nextButt)
                                                           .addComponent(prevButt))
                                                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                       );
        
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        
        newButt.setText("New");
        newButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtActionPerformed(evt);
            }
        });
        
        updateButt.setText("Update");
        updateButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtActionPerformed(evt);
            }
        });
        
        deleteButt.setText("Delete");
        deleteButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtActionPerformed(evt);
            }
        });
        
        saveButt.setText("Save");
        saveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtActionPerformed(evt);
            }
        });
        
        cancelButt.setText("Cancel");
        cancelButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtActionPerformed(evt);
            }
        });
        
        exitButt.setText("Exit");
        
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                                         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                         .addGroup(jPanel3Layout.createSequentialGroup()
                                                   .addContainerGap()
                                                   .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                             .addComponent(saveButt, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                                             .addComponent(newButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                   .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                             .addComponent(cancelButt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                             .addComponent(updateButt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                   .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                             .addComponent(deleteButt, javax.swing.GroupLayout.Alignment.TRAILING)
                                                             .addComponent(exitButt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                   .addContainerGap())
                                         );
        jPanel3Layout.setVerticalGroup(
                                       jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(jPanel3Layout.createSequentialGroup()
                                                 .addGap(12, 12, 12)
                                                 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                           .addComponent(newButt)
                                                           .addComponent(updateButt)
                                                           .addComponent(deleteButt))
                                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                           .addComponent(saveButt)
                                                           .addComponent(cancelButt)
                                                           .addComponent(exitButt))
                                                 .addGap(0, 9, Short.MAX_VALUE))
                                       );
        
        nameList.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        nameList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(nameList);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                  .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                  );
        layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                          .addGap(19, 19, 19)
                                          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                              .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                              .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jScrollPane1))
                                          .addGap(21, 21, 21))
                                );
        
        pack();
    }// </editor-fold>
    
    private void lastButtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try{
            rSet.last();
            displayMe();
        }catch(SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }
    
    private void cancelButtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    private void firstButtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try{
            rSet.first();
            displayMe();
        }catch(SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }
    
    private void nameListMouseClicked(java.awt.event.MouseEvent evt) {
        try
        {
            if(nameList.getSelectedIndex() != -1)
            {
                rSet.beforeFirst();
                
                while(true)
                {
                    rSet.next();
                    if(rSet.getString("name").equals(nameList.getSelectedValue())){
                        break;
                    }
                }
                idNumTxt.setText(rSet.getString("idnumber"));
                nameTxt.setText(rSet.getString("name"));
                gpaTxt.setText(rSet.getString("gpa"));
            }
        }
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }
    
    private void newButtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try {
            curRow = rSet.getRow();
            
            idNumTxt.setText("");
            nameTxt.setText("");
            gpaTxt.setText("");
            deleteButt.setEnabled(false);
            updateButt.setEnabled(false);
            newButt.setEnabled(false);
            firstButt.setEnabled(false);
            nextButt.setEnabled(false);
            prevButt.setEnabled(false);
            lastButt.setEnabled(false);
            newButt.setEnabled(true);
            cancelButt.setEnabled(true);
            saveButt.setEnabled(true);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
        
    }
    
    private void nextButtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try{
            if(rSet.next()){
                displayMe();
            }else{
                rSet.previous();
                JOptionPane.showMessageDialog(this, "End of File");
            }
        }catch(SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }
    
    private void prevButtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try{
            if(rSet.previous()){
                displayMe();
            }else{
                rSet.next();
                JOptionPane.showMessageDialog(this, "Top of File");
            }
        }catch(SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }
    
    private void updateButtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String sId = idNumTxt.getText();
        String sName = nameTxt.getText();
        String sGpa = gpaTxt.getText();
        
        int newId = Integer.parseInt(sId);
        double newGpa = Double.parseDouble(sGpa);
        try{
            rSet.updateInt("idNumber", newId);
            rSet.updateString("name", sName);
            rSet.updateDouble("gpa", newGpa);
            rSet.updateRow();
            JOptionPane.showMessageDialog(this, "Record updated!");
        }catch(SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }
    
    private void deleteButtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try{
            rSet.deleteRow();
            JOptionPane.showMessageDialog(this, "Record deleted!");
            
        }catch(SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }                                          
    
    private void saveButtActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        sId = idNumTxt.getText();
        sName = nameTxt.getText();
        sGpa = gpaTxt.getText();
        
        int newId = Integer.parseInt(sId);
        double newGpa = Double.parseDouble(sGpa);
        String addQuery = "insert into studenttable values(?,?,?)";
        try{
            
            PreparedStatement pstmt = con.prepareStatement(addQuery);
            pstmt.setInt(1, newId);
            pstmt.setString(2, sName);
            pstmt.setDouble(3, newGpa);
            pstmt.execute();
            
            JOptionPane.showMessageDialog(this, "Record added!");
            dlm.addElement(sName);
            nameList.setModel(dlm);
        }catch(SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
    }                                        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentData().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton cancelButt;
    private javax.swing.JButton deleteButt;
    private javax.swing.JButton exitButt;
    private javax.swing.JButton firstButt;
    private javax.swing.JTextField gpaTxt;
    private javax.swing.JTextField idNumTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lastButt;
    private javax.swing.JList<String> nameList;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton newButt;
    private javax.swing.JButton nextButt;
    private javax.swing.JButton prevButt;
    private javax.swing.JButton saveButt;
    private javax.swing.JButton updateButt;
    // End of variables declaration                   
}
